#!/bin/bash

DAVDIR=erp_dav
PUSHDIR=erp_push

rm -rf ../../web/$DAVDIR
rm -rf ../../web/$PUSHDIR

mkdir -p ../../web/$DAVDIR
mkdir -p ../../web/$PUSHDIR

tar -cf - mnesabre composer.json composer.phar remote.php | ( cd ../../web/$DAVDIR; tar -xvf - )

( cd ../../web/$DAVDIR;  chmod +x composer.phar; ./composer.phar install )

( cd ../../web/$PUSHDIR;  git clone https://github.com/fmbiete/Z-Push-contrib.git .; )
( cd mnepush; tar -cf - . ) | ( cd ../../web/$PUSHDIR; tar -xvf - )

 
chown -R www-data:manny ../../web;
chmod -R g+w ../../web;

