#!/bin/bash

ZPUSHDIR=../clone/Z-Push/src
BASEDIR=www
DAVDIR=erp_dav
PUSHDIR=erp_push

rm -rf $BASEDIR/$DAVDIR
rm -rf $BASEDIR/$PUSHDIR

mkdir -p $BASEDIR/$DAVDIR
mkdir -p $BASEDIR/$PUSHDIR

echo 'copy mnesabre'
tar -cf - mnesabre composer.json composer.phar remote.php config.php | ( cd $BASEDIR/$DAVDIR; tar -xf - )

( cd $BASEDIR/$DAVDIR;  chmod +x composer.phar; ./composer.phar install )
( cd $ZPUSHDIR; tar -cf - . ) | ( cd $BASEDIR/$PUSHDIR;  tar -xf -; )

for file in `cd sabre; find . -type f`
do
    echo $file
    if [ -f $BASEDIR/$DAVDIR/$file ]; then
        mv $BASEDIR/$DAVDIR/$file $BASEDIR/$DAVDIR/$file.orig
    fi
done

for file in `cd mnepush; find . -type f`
do
    echo $file
    if [ -f $BASEDIR/$PUSHDIR/$file ]; then
        mv $BASEDIR/$PUSHDIR/$file $BASEDIR/$PUSHDIR/$file.orig
    fi
done

echo 'copy sabre patch'
( cd sabre; tar -cf - . ) | ( cd $BASEDIR/$DAVDIR; tar -xf - )

echo 'copy mnepush'
( cd mnepush; tar -cf - . ) | ( cd $BASEDIR/$PUSHDIR; tar -xf - )
 
echo chown -R www-data:manny $BASEDIR
echo chmod -R g+w $BASEDIR

touch /var/log/mne/erp-z-push.log
touch /var/log/mne/erp-z-push-error.log

chown www-data /var/log/mne/erp-z-push.log
chown www-data /var/log/mne/erp-z-push-error.log

mkdir -p /var/mne/erp/lib/z-push
chown www-data:www-data /var/mne/erp/lib/z-push

